name: example
description: An example of charlatan usage
publish_to: none

environment:
  sdk: ">=2.14-0-0 <3.0.0"

dev_dependencies:
  charlatan:
    path: ../
  dio: ^4.0.0
  lints: ^1.0.1
  test: ^1.16.0
