name: charlatan
description: A library for configuring and providing fake HTTP responses to your dio HTTP client.
version: 0.0.1
homepage: https://github.com/Betterment/charlatan
repository: https://github.com/Betterment/charlatan
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  collection: ^1.15.0-nullsafety.4
  dio: ^4.0.0
  meta: ^1.7.0
  uri: ^1.0.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.0
