# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.5
      - uses: dart-lang/setup-dart@v1.3

      - name: Install dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        uses: invertase/github-action-dart-analyzer@v1

      - name: Run tests and generate coverage report
        run: ./tool/generate_code_coverage.sh

      - uses: codecov/codecov-action@v2
        with:
          files: packages/${{ inputs.package-name }}/coverage/lcov.info
          working-directory: packages/${{ inputs.package-name }}
  
  pana:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.5
      - uses: dart-lang/setup-dart@v1.3

      - name: Install dependencies
        run: |
          dart pub get
          dart pub global activate pana
      
      - name: Verify pub score
        run: ./tool/verify_pub_score.sh
