name: Release

# ignore: RiskyTriggers
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
        with:
          fetch-depth: 0

      - name: Get application token
        id: get_token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        with:
          app-id: ${{ secrets.CI_APP_ID }}
          private-key: ${{ secrets.CI_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Get version
        id: version
        uses: paulhatch/semantic-version@ea50fff3e41d24bb283f22b7343c4b3a314282fb #v5.0.2

      - name: Get Latest Release
        id: latest-release
        uses: pozetroninc/github-action-get-latest-release@d1dafdb6e338bdab109e6afce581a01858680dfb # v0.7.0
        with:
          owner: Betterment
          repo: charlatan
          excludes: prerelease, draft
          token: ${{ github.token }}

      - name: Generate release notes
        id: release-notes
        uses: mikepenz/release-changelog-builder-action@3a70419f3cc01ac7458a4fa44f09726475edfc6a # v3.4.0
        with:
          fromTag: ${{ steps.latest-release.outputs.release }}
          toTag: ${{ github.sha }}
          configuration: .github/workflows/release_changelog_configuration.json
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Setup dart
        uses: dart-lang/setup-dart@d6a63dab3335f427404425de0fbfed4686d93c4f # v1.5.0

      - name: Setup cider
        run: dart pub global activate cider

      - name: Update CHANGELOG and pubspec.yaml
        run: |
          cider version "${{ steps.version.outputs.version }}"
          cat <(echo -e "## ${{ steps.version.outputs.version }} - $(date +%Y-%m-%d) \n\n${{ steps.release-notes.outputs.changelog }}\n\n") CHANGELOG.md > NEW_CHANGELOG.md
          mv NEW_CHANGELOG.md CHANGELOG.md
          git add CHANGELOG.md pubspec.yaml

      - name: Create pull request
        id: create_pull_request
        uses: peter-evans/create-pull-request@2b011faafdcbc9ceb11414d64d0573f37c774b04 # v4.2.3
        with:
          token: ${{ steps.get_token.outputs.token }}
          branch: "bot/prep-release-${{ steps.version.outputs.version }}"
          title: "chore(release): update CHANGELOG and pubspec.yaml for version `${{ steps.version.outputs.version }}` (NOBUMP)"
          commit-message: "chore(release): update CHANGELOG and pubspec.yaml for version `${{ steps.version.outputs.version }}`"
          add-paths: |
            CHANGELOG.md
            pubspec.yaml
          base: main

      - name: Merge pull request
        # ignore: AutomaticMerge
        run: gh pr merge "${{ steps.create_pull_request.outputs.pull-request-number }}" --squash --auto --delete-branch
        env:
          GITHUB_TOKEN: ${{ steps.get_token.outputs.token }}
