name: Release

on:
  push:
    branches: [bt/automate-versioning]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get version
        id: version
        uses: paulhatch/semantic-version@v5.0.2
      - name: Get Latest Release
        id: latest-release
        uses: pozetroninc/github-action-get-latest-release@v0.7.0
        with:
          owner: Betterment
          repo: charlatan
          excludes: prerelease, draft
      - name: Generate release notes
        id: release-notes
        uses: mikepenz/release-changelog-builder-action@3a70419f3cc01ac7458a4fa44f09726475edfc6a # v3.4.0
        with:
          # fromTag: ${{ steps.latest-release.outputs.release }}
          fromTag: v0.3.1
          toTag: v0.4.0 # Needs to be HEAD
          configuration: .github/workflows/release_changelog_configuration.json
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Setup dart and cider
        uses: dart-lang/setup-dart@d6a63dab3335f427404425de0fbfed4686d93c4f # v1.5.0
      - name: Install dependencies
        run: |
          dart pub get
          dart pub global activate cider
      - name: Update CHANGELOG and pubspec.yaml
        run: |
          cider version ${{ steps.version.outputs.version }}
          cat <(echo -e "## ${{ steps.version.outputs.version }} \n\n$${{ steps.release-notes.outputs.changelog }}") CHANGELOG.md > NEW_CHANGELOG.md
          mv NEW_CHANGELOG.md CHANGELOG.md
          git add CHANGELOG.md pubspec.yaml
          echo "CATTING"
          cat CHANGELOG.md
          cat pubspec.yaml
