name: Tag and Create Github Release

on:
  push:
    branches: [main, bt/automate-versioning]
    paths: [CHANGELOG.md, pubspec.yaml]

jobs:
  build:
    runs-on: ubuntu-latest
    if: $(${{ github.event.pusher.username == 'btrautmann' }})
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get application token
        id: get_token
        uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db # v2.1.0
        with:
          application_id: ${{ secrets.CI_APP_ID }}
          application_private_key: ${{ secrets.CI_APP_PRIVATE_KEY }}
      - name: Setup dart
        uses: dart-lang/setup-dart@d6a63dab3335f427404425de0fbfed4686d93c4f # v1.5.0
      - name: Setup cider
        run: dart pub global activate cider
      - name: Get Latest Release
        id: latest-release
        uses: pozetroninc/github-action-get-latest-release@v0.7.0
        with:
          owner: Betterment
          repo: charlatan
          excludes: prerelease, draft
          token: ${{ github.token }}
      - name: Check if should release
        id: should-release
        run: |
          curr_version=$(cider version)
          output_version=v$curr_version
          prev_version=0.3.1
          echo "current version is $curr_version"
          echo "previous version is $prev_version"
          if [ "$curr_version" = "$prev_version" ]; then
            echo "should-release=false" >> $GITHUB_OUTPUT
          else
            echo "should-release=true" >> $GITHUB_OUTPUT
            echo "curr-version=$output_version" >> $GITHUB_OUTPUT
          fi
    #   - name: Create tag
    #     if: ${{ steps.should-release.outputs.should-release }}
    #     run: |
    #       git tag -fa ${{ steps.should-release.outputs.curr-version }} -m "release ${{ steps.should-release.outputs.curr-version }}"
    #       git push -f --tags
    #   - name: Create release
    #     if: ${{ steps.should-release.outputs.should-release }}
    #     uses: ncipollo/release-action@18eadf9c9b0f226f47f164f5373c6a44f0aae169 # v1.11.2
    #     with:
    #       tag: ${{ steps.should-release.outputs.curr-version }}
    #       name: ${{ steps.should-release.outputs.curr-version }}
    #       token: ${{ steps.get_token.output.token }}
    #       generateReleaseNotes: true
