name: Tag and Create Github Release

# ignore: RiskyTriggers
on:
  push:
    branches: [main]
    paths: [CHANGELOG.md, pubspec.yaml]
  workflow_dispatch:

jobs:
  tag_and_create_draft_release:
    runs-on: ubuntu-latest
    if: ${{ github.event.pusher.name == 'betterment-mobile-cicd[bot]' }} || ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Get application token
        id: get_token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        with:
          app-id: ${{ secrets.CI_APP_ID }}
          private-key: ${{ secrets.CI_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
        with:
          token: ${{ steps.get_token.outputs.token }}

      - name: Setup dart
        uses: dart-lang/setup-dart@d6a63dab3335f427404425de0fbfed4686d93c4f # v1.5.0

      - name: Setup cider
        run: dart pub global activate cider

      - name: Get Latest Release
        id: latest-release
        uses: pozetroninc/github-action-get-latest-release@d1dafdb6e338bdab109e6afce581a01858680dfb # v0.7.0
        with:
          owner: Betterment
          repo: charlatan
          excludes: prerelease, draft
          token: ${{ github.token }}

      - name: Check if should release
        id: should-release
        run: |
          pubspec_version=$(cider version)
          curr_version=v$pubspec_version
          prev_version=${{ steps.latest-release.outputs.release }}
          echo "current version is $curr_version"
          echo "previous version is $prev_version"
          if [ "$curr_version" = "$prev_version" ]; then
            echo "should-release=false" >> "$GITHUB_OUTPUT"
          else
            echo "should-release=true" >> "$GITHUB_OUTPUT"
            echo "curr-version=$curr_version" >> "$GITHUB_OUTPUT"
          fi

      - name: Create tag
        if: ${{ steps.should-release.outputs.should-release }}
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git tag -fa "${{ steps.should-release.outputs.curr-version }}" -m "release ${{ steps.should-release.outputs.curr-version }}"
          git push -f --tags

      - name: Create release
        if: ${{ steps.should-release.outputs.should-release }}
        uses: ncipollo/release-action@18eadf9c9b0f226f47f164f5373c6a44f0aae169 # v1.11.2
        with:
          tag: ${{ steps.should-release.outputs.curr-version }}
          name: ${{ steps.should-release.outputs.curr-version }}
          token: ${{ steps.get_token.outputs.token }}
          generateReleaseNotes: true
