name: Semantic PR

on: [pull_request]

permissions:
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@c3cd5d1ea3580753008872425915e343e351ab54 #v5.2.0
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            test
            ci
            chore
          validateSingleCommit: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
