name: Versioning

on:
  push:
    branches: [bt/automate-versioning]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get version
        id: version
        uses: paulhatch/semantic-version@v5.0.2
      - name: Generate release notes
        id: release-notes
        uses: mikepenz/release-changelog-builder-action@3a70419f3cc01ac7458a4fa44f09726475edfc6a # v3.4.0
        with:
          fromTag: v0.3.0
          toTag: v0.4.0
          configuration: .github/workflows/release_changelog_configuration.json
        env:
          GITHUB_TOKEN: ${{ github.token }}
